variable: "sst"

io:
  base_path: "/path/to/ESA_CCI5deg_month_extra/ANOMALY/"
  # Both files have an additional masking of excluding 5x5 grid boxes sic >= 15%
  train_file: "esa_cci_sst_5deg_monthly_1982_2022.nc" # The original training file, 2022 had SIC exclusion 100%
  # train_file: "esa_cci_sst_5deg_monthly_1982_2022_updated.nc" # Updated on 23 July 2025, 2022 SIC exclusion 100% changed to 15%, all other unaffected
  train_var: "sst_anomaly"
  # Below are used to produce the original DCENT analysis
  ellipse_file: "SpatialScales_v1/matern_physical_distances_v_eq_1p5/sst_{mm:02}.nc"
  cov_180_file: "SpatialScales_v1/locally_build_covariances/covariance_{mm:02}_v_eq_1p5_sst_clipped_-180_180.nc"
  cov_360_file: "SpatialScales_v1/locally_build_covariances/covariance_{mm:02}_v_eq_1p5_sst_clipped_0_360.nc"
  idx_180_file: "SpatialScales_v1/locally_build_covariances/row_lookup_{mm:02}_v_eq_1p5_sst_clipped_-180_180.csv"
  # Updated covariance with fully consistent ESA CCI SST files
  # ellipse_file: "SpatialScales_v2/matern_physical_distances_v_eq_1p5/sst_{month:02}.nc"
  # cov_180_file: "SpatialScales_v2/locally_build_covariances/covariance_{month:02}_v_eq_1p5_sst_clipped_-180_180.nc"
  # cov_360_file: "SpatialScales_v2/locally_build_covariances/covariance_{month:02}_v_eq_1p5_sst_clipped_0_360.nc"
  # idx_180_file: "SpatialScales_v2/locally_build_covariances/row_lookup_{month:02}_v_eq_1p5_sst_clipped_-180_180.csv"

fit_params:
  init_value_Lx: 2000.0 # Default: 2000
  init_value_Ly: 2000.0 # Default: 2000
  init_value_theta: 0.0 # Default: 0.0
  Lx_lower_bound: 300.0 # Default: 300.0
  Lx_upper_bound: 30000.0 # Default: 30000.0
  Ly_lower_bound: 300.0 # Default: 300.0
  Ly_upper_bound: 30000.0 # Default: 30000.0
  fit_max_distance: 6667.2 # Default 10000.0
  HadCRUT5_defaults: false # Default: False (use HadCRUT5 default values where not computed)

# Parameters for the ellipse model
model_params:
  anisotropic: true
  rotated: true
  physical_distance: true
  v: 1.5
  unit_sigma: true

cov:
  max_dist: 1.5E+8 # Default: 6000
  max_allowed_lx: 29995.0 # If Lx > this value; set Lx to Ly (fix a problem specific to a grid point near Svalbard)
  fill_before_clipping: False # Default: True
  off_diag_fill_value: 0.0 # Default: np.nan
  eigenvalue_clip_method: "explained_variance" # Default: explained_variance
  clip_params:
    explained_variance:
      target_variance_fraction: 0.95
    laloux_clip:
      # num_grid_pts: 2592,
      num_time_pts: 40,
