# Configuration for stitching DCENT from SST and LSAT files using
# Weight files

sst_path: "/path/to/kriged_member_{member:03d}.nc"
sst_var_name: "sst_anom_perturbed"

lsat_path: "/path/to/kriged_member_{member:03d}.nc"
lsat_var_name: "lsat_anom_perturbed"

land_mask_path: "/path/to/land_lowres_kernel_esa_hybrid.nc"
land_mask_var_name: "mask"
ice_mask_path: "/path/to/hadisst2_esa_cci_merged_5x5_1850_2024.nc"
ice_mask_var_name: "sea_ice_area_fraction"

out_path: "/path/to/kriged_member_{member:03d}.nc"
out_var_name: "combined_perturbed"

e0: 1
ef: 200
